config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pragprog Books Online Store</title>
		<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
		<%= stylesheet_link_tag "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body class="<%= controller.controller_name %>">
		<div class="container">
			<div id="banner" class="row">
				<div class="span4">
					<%= image_tag("http://placehold.it/200x100") %>
				</div>
				<div id="page_title" class="span12">				
					<%= @page_title || "EscuelaWeb Shop Cart" %>
				</div>			
			</div>
		</div>
		<div class="container">
		<div id="columns" class="row">
			<div id="side" class="span4">
				<ul>
					<li>
						<%=link_to 'Home', '/' %>
					</li>
					<li>
						<%=link_to 'Products', products_path() %>
					</li>
				</ul>
			</div>
			<div id="main" class="span12">
				<%= yield %>
			</div>
		</div>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pragprog Books Online Store</title>
		<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
		<%= stylesheet_link_tag "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tag %>
	</head>
	<body class="<%= controller.controller_name %>">
		<div class="container">
			<div id="banner" class="row">
				<div class="span4">
					<%= image_tag("http://placehold.it/200x100") %>
				</div>
				<div id="page_title" class="span12">				
					<%= @page_title || t('title') %>
				</div>			
			</div>
		</div>
		<div class="container">
		<div id="columns" class="row">
			<div id="side" class="span4">
				<% if @cart %>
				 	<div id="cart">
				 		<%= render @cart %>
				 	</div>
			 	<% end %>
				
				<ul>
					<li>
						<%=link_to t(:home), '/' %>
					</li>
				</ul>
				<% if session[:user_id] %>
					<ul>
						<li><%=link_to t(:home), products_path() %></li>
						<li><%=link_to t(:prodcuts), orders_path() %></li>
						<li><%= link_to t(:users), users_path %></li>
					</ul>
					<%= button_to 'logout', logout_path, method: :delete, :class=>'btn primary' %>
				<% end %>
			</div>
			<div id="main" class="span12">
				<%= yield %>
			</div>
		</div>
		</div>
	</body>
</html>